### ISSUE TITLE
Strana struttura directory di output

### ISSUE THREAD

**Issue by MarcoBuster** [SimpoLab/unimi-dl#2]
Dopo aver scaricato da Ariel con il tool ho notato che la struttura della directory di output è molto strana:
![immagine](https://user-images.githubusercontent.com/14850025/118097896-8bcef680-b3d3-11eb-88ee-aa980263116a.png)

Sto usando Python 3.9.5 con l'ultima versione disponibile su PyPi del vostro tool. 
Ho richiamato il comando con i seguenti parametri:
```bash
unimi-dl -p ariel -v https://XXXXXX.ariel.ctu.unimi.it/v5/frm3/ThreadList.aspx\?XXXXXXXXXXXXXXXXXXXX
```
e non ha ritornato nessun erorre.
Allego i log: [paste](https://paste.studentiunimi.it/paste/I+vb1Scc#d4aXirI5Ti3LB5uUeuJAPxNtX7rDAgZOfmw-kITGKf5).

**Comment by sgorblex** [comment]
Ciao @MarcoBuster, grazie per la tua segnalazione. Il bug era dovuto a una mia svista durante il recente refactoring e dovrebbe essere stato risolto con la versione `0.2.1` (`pip3 install --upgrade unimi-dl`). Buon download!
